"use client";
import { useEffect, useState } from "react";
import { CalendarDays, Edit3, FileText, Pin, Plus, Search, StickyNote, Trash2, X } from "lucide-react";
import toast from "react-hot-toast";

const CATEGORIES=["All","General","Student","Class","Payment","Important"];
const styles={General:"bg-slate-100 text-slate-600",Student:"bg-blue-50 text-blue-700",Class:"bg-violet-50 text-violet-700",Payment:"bg-emerald-50 text-emerald-700",Important:"bg-amber-50 text-amber-700"};
const input="mt-1.5 block min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-semibold text-slate-900 shadow-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10";
const blank=()=>({title:"",content:"",category:"General",pinned:false});
const date=v=>new Date(v).toLocaleDateString("en-BD",{day:"numeric",month:"short",year:"numeric"});

export default function NotesPage(){
 const [notes,setNotes]=useState([]),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[form,setForm]=useState(blank());
 const load=async()=>{setLoading(true);try{const p=new URLSearchParams();if(search.trim())p.set("search",search.trim());if(category!=="All")p.set("category",category);const r=await fetch(`/api/notes?${p}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw Error(j.error);setNotes(j)}catch(e){toast.error(e.message||"Failed to load notes")}finally{setLoading(false)}};
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[search,category]);
 const add=()=>{setEditing(null);setForm(blank());setModal(true)};
 const edit=n=>{setEditing(n);setForm({title:n.title,content:n.content,category:n.category,pinned:n.pinned});setModal(true)};
 const save=async e=>{e.preventDefault();if(!form.title.trim()||!form.content.trim())return toast.error("Title and note are required");setSaving(true);try{const r=await fetch(editing?`/api/notes/${editing._id}`:"/api/notes",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),j=await r.json();if(!r.ok)throw Error(j.error);toast.success(editing?"Note updated":"Note saved");setModal(false);load()}catch(x){toast.error(x.message||"Save failed")}finally{setSaving(false)}};
 const remove=async n=>{if(!confirm(`Delete “${n.title}”?`))return;try{const r=await fetch(`/api/notes/${n._id}`,{method:"DELETE"}),j=await r.json();if(!r.ok)throw Error(j.error);toast.success("Note deleted");load()}catch(e){toast.error(e.message||"Delete failed")}};
 return <div className="space-y-5 pb-6">
  <section className="relative overflow-hidden rounded-[28px] bg-slate-950 px-5 py-6 text-white shadow-lg sm:px-7"><div className="absolute -right-10 -top-12 h-40 w-40 rounded-full bg-blue-500/20 blur-2xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-blue-300"><StickyNote className="h-4 w-4"/><span className="text-xs font-extrabold uppercase tracking-[.16em]">Personal workspace</span></div><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">Notes</h1><p className="mt-1 text-sm leading-6 text-slate-300">Keep important student, class and payment information in one place.</p></div><button onClick={add} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 text-sm font-extrabold text-slate-900"><Plus className="h-5 w-5"/>Add Note</button></div></section>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat I={FileText} l="Total Notes" v={notes.length}/><Stat I={Pin} l="Pinned" v={notes.filter(n=>n.pinned).length}/><div className="hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:block"><p className="text-xs font-bold text-slate-400">Quick tip</p><p className="mt-1 text-sm font-extrabold text-slate-800">Pin anything you need often.</p></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notes..." className="min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm font-semibold outline-none focus:border-blue-500 focus:bg-white"/></div><div className="flex gap-1 overflow-x-auto">{CATEGORIES.map(c=><button key={c} onClick={()=>setCategory(c)} className={`min-h-10 shrink-0 rounded-xl px-3 text-xs font-extrabold ${category===c?"bg-slate-900 text-white":"bg-slate-50 text-slate-500"}`}>{c}</button>)}</div></div></section>
  {loading?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(x=><div key={x} className="h-52 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:notes.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{notes.map(n=><NoteCard key={n._id} n={n} edit={edit} remove={remove}/>)}</div>:<div className="rounded-[28px] border border-dashed border-slate-300 bg-white px-5 py-16 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><StickyNote className="h-7 w-7"/></div><h2 className="mt-4 text-lg font-extrabold text-slate-900">No notes found</h2><p className="mt-1 text-sm text-slate-500">Start keeping track of important information and reminders.</p><button onClick={add} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-extrabold text-white"><Plus className="h-4 w-4"/>Create first note</button></div>}
  {modal&&<div className="fixed inset-0 z-[200] flex items-center justify-center bg-slate-950/55 p-3 backdrop-blur-sm sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setModal(false)}}><form onSubmit={save} className="flex max-h-[calc(100dvh-1.5rem)] w-full max-w-xl flex-col overflow-hidden rounded-[28px] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-5 py-5 sm:px-7"><div><p className="text-xs font-extrabold uppercase tracking-wider text-blue-600">{editing?"Edit note":"New note"}</p><h2 className="mt-1 text-2xl font-extrabold text-slate-900">{editing?"Update your note":"Write a note"}</h2></div><button type="button" onClick={()=>setModal(false)} className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100"><X className="h-5 w-5"/></button></div><div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-5 py-5 sm:px-7"><label className="block text-sm font-extrabold text-slate-700">Title<input required maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input} placeholder="e.g. Batch 3 Math Exam"/></label><label className="block text-sm font-extrabold text-slate-700">Note<textarea required maxLength={5000} rows={7} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className={`${input} resize-none`} placeholder="Write anything you need to remember..."/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-extrabold text-slate-700">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={input}>{CATEGORIES.filter(x=>x!=="All").map(x=><option key={x}>{x}</option>)}</select></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border border-slate-200 bg-slate-50 px-3.5 text-sm font-extrabold"><input type="checkbox" checked={form.pinned} onChange={e=>setForm({...form,pinned:e.target.checked})} className="h-4 w-4 accent-blue-600"/>Pin this note</label></div></div><div className="border-t border-slate-100 p-4 sm:px-7"><button disabled={saving} className="min-h-12 w-full rounded-2xl bg-blue-600 font-extrabold text-white disabled:opacity-60">{saving?"Saving...":editing?"Update Note":"Save Note"}</button></div></form></div>}
 </div>;
}
function Stat({I,l,v}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><I className="h-4 w-4"/></div><p className="mt-3 text-xs font-bold text-slate-400">{l}</p><p className="text-xl font-extrabold text-slate-900">{v}</p></div>}
function NoteCard({n,edit,remove}){return <article className={`overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${n.pinned?"border-amber-200":"border-slate-200"}`}><div className={`h-1 ${n.pinned?"bg-amber-400":"bg-blue-500"}`}/><div className="p-4 sm:p-5"><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2">{n.pinned&&<span className="flex h-8 w-8 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Pin className="h-4 w-4"/></span>}<span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ${styles[n.category]}`}>{n.category}</span></div><div className="flex gap-1"><button onClick={()=>edit(n)} className="flex h-9 w-9 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100"><Edit3 className="h-4 w-4"/></button><button onClick={()=>remove(n)} className="flex h-9 w-9 items-center justify-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div></div><h2 className="mt-4 line-clamp-2 text-base font-extrabold leading-6 text-slate-900">{n.title}</h2><p className="mt-2 line-clamp-5 whitespace-pre-wrap text-sm leading-6 text-slate-500">{n.content}</p><div className="mt-5 flex items-center gap-1.5 border-t border-slate-100 pt-3 text-[11px] font-semibold text-slate-400"><CalendarDays className="h-3.5 w-3.5"/>Updated {date(n.updatedAt)}</div></div></article>}
